sudo: false
language: node_js
node_js: "node"

install:
  - yarn install
  - yarn global add codecov

script:
  - yarn test --coverage

after_success:
  - codecov

deploy:
  provider: script
  script: yarn deploy-storybook --ci
  on:
    branch: master
