sudo: false
language: node_js
node_js: "node"

install:
  - yarn install
  - yarn global add codecov

script:
  - yarn test --coverage

after_success:
  - codecov

before_deploy:
  - yarn build-storybook

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: storybook-static
  on:
    branch: master
